# Generated by Django 5.1.5 on 2025-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
