# Generated by Django 5.1.2 on 2025-01-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
