# Generated by Django 5.1.2 on 2025-01-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0002_delete_product'),
        ('Scanner', '0002_uploadedimage_delete_product'),
    ]

    operations = [
    ]
